### ISSUE TITLE
rebase 1.42

### ISSUE THREAD

**Issue by turnstep** [lkinley/Net-SSH-Perl#1]
Could you rebase this to 1.42? It looks like this (awesome) work is based on 1.38

**Comment by lkinley** [comment]
Yes, I did this work when 1.38 was the most current.  I have merged 1.38 -> 1.42 changes into master

My long-term goals are to reduce module dependencies.  I have some more commits in a different branch that switch to using CryptX for AES and digests and include the Crypt::OpenBSD::Blowfish and Crypt::OpenSSH::ChachaPoly modules in the distribution.  I am unsure if bundling those is best, however.

Ultimately I'd like to get away from using Pari by writing a big int library wrapper around libtommath/libtomcrypt.

**Comment by choroba** [comment]
I tried to merge the changes into the original repo:

https://github.com/renormalist/Net-SSH-Perl/pull/11
