### ISSUE TITLE
Could not find a way to prevent Net::SSH::Perl from exiting the script if the detination port has no service.

### ISSUE THREAD

**Issue by medeiros1** [lkinley/Net-SSH-Perl#20]
Hi, thanks for this well working module, it does a great job.
Unfortunately I could not find a way to prevent the script exiting when the destination port is not under service:
If the port is reachable all works fine.
---------------------------------------------------------------------------------------------------
my $remoteport="3302";
my $ssh = Net::SSH::Perl->new($ConfigP::remotehost,options => ["Port $remoteport"]);
^^^^^^^^ exits after the line above, if the port does not provide a service ^^^^^^^^
$ssh->login($ConfigP::remoteuser,$ConfigP::remotepass);
my($stdout, $stderr, $exit) = $ssh->cmd("<some command>")
---------------------------------------------------------------------------------------------------
Is there a method in the module to check for a port under service instead of exiting ?

Regards Rolf

**Comment by sensei-hacker** [comment]
You can do:

```
my $ssh;
eval { $ssh = Net::SSH::Perl->new($ConfigP::remotehost,options => ["Port $remoteport"]) };
warn $@ if $@;



```

**Comment by medeiros1** [comment]
Thanks for the trick ! I didn't realize that eval can be used to prevent a script from exiting when a routine exits. After you wrote it, it became clear to me that it works.

**Comment by rwp0** [comment]
I think the newer `try`/`catch` syntax can be used here in place of `eval` as well.

**Comment by briandfoy** [comment]
I've forked this project at [briandfoy/net-ssh-perl](https://github.com/briandfoy/net-ssh-perl), and you can reopen this issue there if you'd like.  Otherwise, I'll add it myself at some later time. See #22.

If you include text like `transferred from linkley/Net-SSH-Perl#20`, GitHub should make a reference between the two issues.

But, I think this issue has been resolved and you can close it.

**Comment by medeiros1** [comment]
Thanks, the eval method worked for me as desired.
