### ISSUE TITLE
t/05-cipher.t fails with preinstalled Crypt::OpenSSH::ChachaPoly

### ISSUE THREAD

**Issue by renormalist** [lkinley/Net-SSH-Perl#5]
This is a "proxy ticket" for RT-117272 and similar tickets.

Essentially the problem is that

  `t/05-cipher.t`

fails when `Crypt::OpenSSH::ChachaPoly` is already installed before with an error like

>   The key must be 128 or 256 bits long at .../Net/SSH/Perl/Cipher/ChachaPoly.pm line 36.

All participants from

  https://rt.cpan.org/Ticket/Display.html?id=117272
  https://rt.cpan.org/Ticket/Display.html?id=115382
  https://rt.cpan.org/Ticket/Display.html?id=115669
  https://rt.cpan.org/Ticket/Display.html?id=114077

are invited to contribute here.

**Comment by lkinley** [comment]
Bug #115669 can be solved with passing the option:
'Ciphers +aes128-cbc'

ie:  
my $ssh = Net::SSH::Perl->new('host', options => [ 'Ciphers +aes128-cbc' ] );

CBC ciphers are not enabled by default (not secure enough).

**Comment by lkinley** [comment]
Bug #114077 will be solved in upcoming 2.08
Bug #117272 should not be a problem anymore since the modules are now included in the distribution.
Bug #115382 should be solved in 2.02+
