### ISSUE TITLE
Getting odd warnings on several hosts that I am connecting to...

### ISSUE THREAD

**Issue by yayster** [lkinley/Net-SSH-Perl#8]
[ssh_session_issue.txt](https://github.com/lkinley/Net-SSH-Perl/files/926937/ssh_session_issue.txt)

Please see the attached file.  I am not understanding why I see these warning on a percentage of hosts that I am connecting to.  Any feedback would be appreciated.

**Comment by lkinley** [comment]
It appears that you must have some "interesting" entries in your known_hosts file(s).
By interesting I mean invalid.

**Comment by lkinley** [comment]
I will add some more checks to ignore such entries.

**Comment by yayster** [comment]
Thank you for the feedback!  
While I wait for the update, I removed my ~/.ssh/known_hosts* files and the behavior is much better.
