### ISSUE TITLE
SSH2MP: A question and an issue (with Net::SFTP)

### ISSUE THREAD

**Issue by whindsx** [lkinley/Net-SSH-Perl#9]
It appears that Net::SSH::Perl::Util::SSH2MP was removed around version 2.01 -> 2.02. Which causes the following error in Net::SFTP v0.10:
>Undefined subroutine &Net::SFTP::Buffer::bin2mp called at /usr/local/lib/perl5/site_perl/5.18.0/Net/SFTP/Buffer.pm line 19.

The bin2mp function was imported into Net::SFTP::Buffer via: 
```Perl
use Net::SSH::Perl::Util qw( :ssh2mp );
```
But now it's gone from Net::SSH::Perl::Util.

So the question is why was lib/Net/SSH/Perl/Util/SSH2MP.pm removed?

**Comment by lkinley** [comment]
SSHMP required Math::Pari, which is a problematic library in the licensing and some distros won’t include it.

It can also be a pain to compile on many platforms.  I went to great lengths to excise it from the code.

If you want a Net::SFTP that works with v2, use this:
https://github.com/lkinley/Net-SFTP

I hope to get this on CPAN soon.

**Comment by whindsx** [comment]
I tested your Net::SFTP with Net::SSH::Perl v2.12 on my system (Solaris 11.3 x86) and it seems fine.

I guess those folks that are on Net::SSH::Perl between 2.01 and 2.12 are out of luck since your Net::SFTP depends on Net::SSH::Perl 2.12?

**Comment by lkinley** [comment]
It will work with 2.09, but 2.09 has some bugs.  I put 2.12 as the requirement to avoid those bugs, but the guy who posts the CPAN releases has not done 2.12 yet.

**Comment by lkinley** [comment]
2.12 was released, but 2.13 coming soon to fix some other bugs that only affect deprecated ciphers.
